"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GesReg.py']
DATA_FILES = [
    'models',
    'database',
    'media',
    'driver',
]
OPTIONS = {'iconfile': '/Volumes/Data/Computing Science/VTC/AI '
             'Specialist/Research/encoding/app_icon.icns',
           'plist': {
                'CFBundleName': "GesReg",
                'CFBundleDisplayName': "GesReg",
                'CFBundleGetInfoString': "Gesture Recognizer",
                'CFBundleIdentifier': "com.cszone.osx.gesreg",
                'CFBundleVersion': "0.1.0",
                'CFBundleShortVersionString': "0.1.0",
                'NSHumanReadableCopyright': u"Copyright © 2021, Nguyen Minh Anh, All Rights Reserved"
            },
           "includes": ["os", "platform", "tkinter"],
           }

setup(
    name="GesReg",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
